(require 'cl-lib)

(defvar arete-root
  (or (getenv "ARETE_ROOT") default-directory))

(defvar arete-modus-themes-path
  (or (getenv "ARETE_MODUS_THEMES_PATH")
    (expand-file-name "~/.config/emacs.bak/elpa/modus-themes-20260418.1313")))

(add-to-list 'load-path arete-modus-themes-path)

(defvar arete-modus-themes
  '((modus-operandi . light)
     (modus-operandi-tinted . light)
     (modus-operandi-deuteranopia . light)
     (modus-operandi-tritanopia . light)
     (modus-vivendi . dark)
     (modus-vivendi-tinted . dark)
     (modus-vivendi-deuteranopia . dark)
     (modus-vivendi-tritanopia . dark)))

(defvar arete-modus-face-map
  '((Normal . default)
     (NormalFloat . tooltip)
     (FloatBorder . vertical-border)
     (Cursor . cursor)
     (CursorLine . hl-line)
     (ColorColumn . fill-column-indicator)
     (Visual . region)
     (VisualNOS . secondary-selection)
     (Search . match)
     (IncSearch . isearch)
     (CurSearch . isearch)
     (Substitute . query-replace)
     (LineNr . line-number)
     (CursorLineNr . line-number-current-line)
     (SignColumn . fringe)
     (FoldColumn . fringe)
     (Folded . shadow)
     (StatusLine . mode-line)
     (StatusLineNC . mode-line-inactive)
     (TabLine . tab-line)
     (TabLineFill . tab-line)
     (TabLineSel . tab-line-tab-current)
     (VertSplit . vertical-border)
     (WinSeparator . vertical-border)
     (Directory . dired-directory)
     (Title . font-lock-function-name-face)
     (Question . minibuffer-prompt)
     (MoreMsg . success)
     (WarningMsg . warning)
     (ErrorMsg . error)
     (Error . error)
     (Todo . font-lock-warning-face)
     (NonText . shadow)
     (SpecialKey . escape-glyph)
     (Pmenu . completions-common-part)
     (PmenuSel . completions-highlight)
     (PmenuSbar . scroll-bar)
     (PmenuThumb . highlight)
     (WildMenu . completions-highlight)
     (Comment . font-lock-comment-face)
     (Constant . font-lock-constant-face)
     (String . font-lock-string-face)
     (Character . font-lock-string-face)
     (Number . font-lock-constant-face)
     (Boolean . font-lock-constant-face)
     (Float . font-lock-constant-face)
     (Identifier . font-lock-variable-name-face)
     (Function . font-lock-function-name-face)
     (Statement . font-lock-keyword-face)
     (Conditional . font-lock-keyword-face)
     (Repeat . font-lock-keyword-face)
     (Label . font-lock-keyword-face)
     (Operator . font-lock-operator-face)
     (Keyword . font-lock-keyword-face)
     (Exception . font-lock-keyword-face)
     (PreProc . font-lock-preprocessor-face)
     (Include . font-lock-preprocessor-face)
     (Define . font-lock-preprocessor-face)
     (Macro . font-lock-preprocessor-face)
     (PreCondit . font-lock-preprocessor-face)
     (Type . font-lock-type-face)
     (StorageClass . font-lock-type-face)
     (Structure . font-lock-type-face)
     (Typedef . font-lock-type-face)
     (Special . font-lock-builtin-face)
     (SpecialChar . font-lock-negation-char-face)
     (Tag . font-lock-doc-markup-face)
     (Delimiter . font-lock-delimiter-face)
     (SpecialComment . font-lock-doc-face)
     (Debug . font-lock-warning-face)
     (Underlined . link)
     (Ignore . shadow)))

(defvar arete-modus-links
  '(("@comment" . "Comment")
     ("@constant" . "Constant")
     ("@constant.builtin" . "Special")
     ("@constructor" . "Special")
     ("@function" . "Function")
     ("@function.builtin" . "Special")
     ("@keyword" . "Keyword")
     ("@keyword.conditional" . "Conditional")
     ("@keyword.repeat" . "Repeat")
     ("@keyword.exception" . "Exception")
     ("@label" . "Label")
     ("@module" . "Include")
     ("@number" . "Number")
     ("@operator" . "Operator")
     ("@property" . "Identifier")
     ("@punctuation" . "Delimiter")
     ("@string" . "String")
     ("@tag" . "Tag")
     ("@type" . "Type")
     ("@variable" . "Identifier")
     ("@variable.builtin" . "Special")
     ("DiagnosticError" . "Error")
     ("DiagnosticWarn" . "WarningMsg")
     ("DiagnosticInfo" . "MoreMsg")
     ("DiagnosticHint" . "Question")
     ("DiagnosticOk" . "MoreMsg")))

(defvar arete-captured-faces nil)

(defun arete-lua-string (value)
  (format "%S" value))

(defun arete-lua-key (key)
  (cond
    ((numberp key) (format "[%d]" key))
    ((symbolp key) (format "[%s]" (arete-lua-string (symbol-name key))))
    ((stringp key) (format "[%s]" (arete-lua-string key)))
    (t (format "[%s]" (arete-lua-string (format "%s" key))))))

(defun arete-lua-value (value level)
  (cond
    ((stringp value) (arete-lua-string value))
    ((numberp value) (number-to-string value))
    ((eq value t) "true")
    ((eq value :json-false) "false")
    ((listp value) (arete-lua-table value level))
    (t "nil")))

(defun arete-lua-table (alist &optional level)
  (setq level (or level 1))
  (let ((indent (make-string level ?\t))
         (child-indent (make-string (1+ level) ?\t)))
    (concat "{\n"
      (mapconcat
        (lambda (item)
          (format "%s%s = %s,"
            child-indent
            (arete-lua-key (car item))
            (arete-lua-value (cdr item) (1+ level))))
        alist
        "\n")
      "\n"
      indent
      "}")))

(defun arete-face-plist (face)
  (let ((spec (alist-get face arete-captured-faces)))
    (when spec
      (let (plist)
        (dolist (entry (car spec))
          (let ((properties (cdr entry)))
            (while properties
              (let ((key (pop properties))
                     (value (pop properties)))
                (unless (eq key :inherit)
                  (setq plist (plist-put plist key value)))
                (when (and (eq key :inherit) value)
                  (setq plist (append plist (list :inherit value))))))))
        plist))))

(defun arete-inherit-member-p (needle inherit)
  (cond
    ((eq inherit needle) t)
    ((listp inherit) (memq needle inherit))
    (t nil)))

(defun arete-nvim-spec (face)
  (let* ((plist (arete-face-plist face))
          (inherit (plist-get plist :inherit))
          (fg (plist-get plist :foreground))
          (bg (plist-get plist :background))
          (weight (plist-get plist :weight))
          (slant (plist-get plist :slant))
          (underline (plist-get plist :underline))
          spec)
    (when (and (stringp fg) (not (string-match-p "unspecified" fg)))
      (push (cons "fg" fg) spec))
    (when (and (stringp bg) (not (string-match-p "unspecified" bg)))
      (push (cons "bg" bg) spec))
    (when (or (eq weight 'bold)
            (arete-inherit-member-p 'bold inherit)
            (arete-inherit-member-p 'modus-themes-bold inherit))
      (push (cons "bold" t) spec))
    (when (or (eq slant 'italic)
            (arete-inherit-member-p 'italic inherit)
            (arete-inherit-member-p 'modus-themes-slant inherit))
      (push (cons "italic" t) spec))
    (when underline
      (push (cons "underline" t) spec))
    (nreverse spec)))

(defun arete-terminal-colors (theme)
  (let ((names '(fg-term-black fg-term-red fg-term-green fg-term-yellow
                  fg-term-blue fg-term-magenta fg-term-cyan fg-term-white
                  fg-term-black-bright fg-term-red-bright fg-term-green-bright
                  fg-term-yellow-bright fg-term-blue-bright fg-term-magenta-bright
                  fg-term-cyan-bright fg-term-white-bright))
         colors)
    (cl-loop for index from 0
      for name in names
      for color = (modus-themes-get-color-value name nil theme)
      when (stringp color)
      do (push (cons index color) colors))
    (nreverse colors)))

(defun arete-theme-highlights ()
  (let (highlights)
    (dolist (entry arete-modus-face-map)
      (let ((spec (arete-nvim-spec (cdr entry))))
        (when spec
          (push (cons (symbol-name (car entry)) spec) highlights))))
    (dolist (entry arete-modus-links)
      (push (cons (car entry) (list (cons "link" (cdr entry)))) highlights))
    (nreverse highlights)))

(defun arete-write-theme (theme background)
  (let* ((name (symbol-name theme))
          (path (expand-file-name (format "lua/arete/themes/modus/%s.lua" name) arete-root))
          (colors-path (expand-file-name (format "colors/%s.lua" name) arete-root)))
    (make-directory (file-name-directory path) t)
    (make-directory (file-name-directory colors-path) t)
    (with-temp-file path
      (insert "return {\n")
      (insert (format "\t[\"background\"] = %S,\n" (symbol-name background)))
      (insert "\t[\"highlights\"] = ")
      (insert (arete-lua-table (arete-theme-highlights)))
      (insert ",\n\t[\"name\"] = ")
      (insert (arete-lua-string name))
      (insert ",\n\t[\"terminal\"] = ")
      (insert (arete-lua-table (arete-terminal-colors theme)))
      (insert ",\n}\n"))
    (with-temp-file colors-path
      (insert (format "require(\"arete\").load(\"%s\")\n" name)))))

(defun arete-import-theme (theme background)
  (setq arete-captured-faces nil)
  (load-theme theme t)
  (arete-write-theme theme background)
  (disable-theme theme))

(let ((original-custom-theme-set-faces (symbol-function 'custom-theme-set-faces)))
  (cl-letf (((symbol-function 'custom-theme-set-faces)
              (lambda (theme &rest args)
		(setq arete-captured-faces args)
		(apply original-custom-theme-set-faces theme args))))
    (require 'modus-themes)
    (dolist (entry arete-modus-themes)
      (arete-import-theme (car entry) (cdr entry)))))

(princ (format "Imported %d Modus themes into %s\n" (length arete-modus-themes) arete-root))
